# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  capstone_admin:
    image: capstoneadmin
    build:
      context: .
      dockerfile: Capstone.Admin/Dockerfile
    ports:
      - 5255:5255
    depends_on:
      - capstone_db
  capstone_enduser:
    image: capstoneenduser
    build:
      context: .
      dockerfile: Capstone.EndUser/Dockerfile
    ports:
      - 5256:5256
    depends_on:
      - capstone_db
  capstone_flight:
    image: capstoneflight
    build:
      context: .
      dockerfile: Capstone.Flight/Dockerfile
    ports:
      - 5257:5257
    depends_on:
      - capstone_db
  capstone_gateway: 
    image: capstonegateway
    build:
      context: .
      dockerfile: Capstone.Gateway/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - capstone_db
      - capstone_admin
      - capstone_enduser
      - capstone_flight
  capstone_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  capstone_webapp:
    image: myflightapp
    build:
      context: .
      dockerfile: my-flight-app/Dockerfile
    ports:
      - 3000:3000
volumes:
  db:
    driver: local

