
//@gateway=http://localhost:8000/api/v1.0/flight
@gateway=http://localhost:8000/api/v1.0/flight

//url
@adminRegisterUrl=admin/register
@adminLoginUrl=admin/login
@addAirlineUrl=airline/register
@airlineBlockUnblockUrl=airline/block
@searchFlightUrl=search
@bookFlightUrl= booking
@pnrUrl=ticket
@emailHistoryUrl=booking/history
@cancelPnrUrl=booking/cancel

//variables
@flightId= 12
@block=true
@pnr=BLR-DEL-OW-21411D9F
@dateTime = 2023-04-09
@email=s.a@g.com
@cancelPnr=BLR-DEL-RT-F77F0C67

@adminToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZmxpZ2h0YWRtaW4iLCJqdGkiOiIzNjI1ZTYzMi00NTVhLTQzMjItYjUxZC02YTBhYWE1ODNjNzMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3VzZXJkYXRhIjoiZTQ4NTNkZGEtNjE5OS00ZTVmLWJjMDEtZGZlZTRkYWExZjcxIiwiZXhwIjoxNjg0NzAyNjUxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxOTkiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUxOTkifQ.0ut8jvE7bVoLjRIMFBqp2sJALNmu4WAGFXUhXuAPxHM

//admin register
###
POST {{gateway}}/{{adminRegisterUrl}}
Content-Type: application/json

{
  "username": "flightadmin",
  "email": "flightadmin@capstone.com",
  "firstName": "flight",
  "lastName": "admin",
  "fullName": "flight admin",
  "password": "123456"
}

//admin login
###
POST {{gateway}}/{{adminLoginUrl}}
Content-Type: application/json

{
  "username": "flightadmin",
  "password": "123456"
}

//add airline
###
POST {{gateway}}/{{addAirlineUrl}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "flightNumber": "F-0021",
  "airline": "Vistara",
  "from": "DEL",
  "to": "BLR",
  "startAt": "11:00",
  "endAt":"12:00",
  "days": [
    "Monday", "Tuesday"
  ],
  "instrument": "Boeing",
  "businessClassSeats": 10,
  "nonBusinessClassSeats": 10,
  "rows": 5,
  "cost": 1000,
  "isVeg": true,
  "isNonVeg": true
}

//block or unblock flight
###
PUT  {{gateway}}/{{airlineBlockUnblockUrl}}/{{flightId}}/{{block}}
Authorization: Bearer {{adminToken}}


//return trip search flight
###
POST {{gateway}}/{{searchFlightUrl}}
Content-Type: application/json

{
  "from": "BLR",
  "to": "DEL",
  "fromTravelDate": "2023-05-22",
  "returnTravelDate": "2023-05-23",
  "tripType": "RoundTrip",
  "mealType": "Veg"
}

//one way search flight
###
POST {{gateway}}/{{searchFlightUrl}}
Content-Type: application/json

{
  "from": "BLR",
  "to": "DEL",
  "fromTravelDate": "2023-05-22",
  "tripType": "OneWay",
  "mealType": "Veg"
}

//one book flight
###
POST {{gateway}}/{{bookFlightUrl}}
Content-Type: application/json

{
  "fromFlightId": 1,
  "userEmail": "s.a@g.com",
  "passengers": [
    {
      "firstName": "sumit",
      "lastName": "agrawal",
      "age": 35,
      "mealType": "Veg",
      "seatNumber": 1
    },
    {
      "firstName": "a",
      "lastName": "b",
      "age": 30,
      "mealType": "Veg",
      "seatNumber": 2
    }
  ],
  "fromTravelDate": "2023-05-22",
  "tripType": "OneWay"
}

//round trip book flight
###
POST {{gateway}}/{{bookFlightUrl}}
Content-Type: application/json

{
  "fromFlightId": 9,
  "returnFlightId": 10,
  "userEmail": "s.a@g.com",
  "passengers": [
    {
      "firstName": "sumit",
      "lastName": "agrawal",
      "age": 35,
      "mealType": "Veg",
      "seatNumber": 1
    },
    {
      "firstName": "a",
      "lastName": "b",
      "age": 30,
      "mealType": "Veg",
      "seatNumber": 2
    }
  ],
  "fromTravelDate": "2023-05-22",
  "tripType": "RoundTrip",
  "returnTravelDate":"2023-05-23"
}

//pnr detail
###
GET {{gateway}}/{{pnrUrl}}/{{pnr}}

//history by email id
###
GET {{gateway}}/{{emailHistoryUrl}}/{{email}}


//cancel pnr
###
DELETE {{gateway}}/{{cancelPnrUrl}}/{{cancelPnr}}



